import type { SiteContent, SocialPlatform } from './types';

export const INITIAL_SITE_CONTENT: SiteContent = {
  profile: {
    name: 'Alex Doe',
    bio: 'Digital creator, minimalist, and coffee enthusiast. Sharing my journey one link at a time.',
    avatarUrl: 'https://i.postimg.cc/Y0ZrPysw/maz.jpg',
  },
  links: [
    {
      id: '2',
      platform: 'instagram',
      url: 'https://instagram.com/your-profile',
    },
    {
      id: '4',
      platform: 'tiktok',
      url: 'https://tiktok.com/@your-profile',
    },
  ],
  footerText: `© ${new Date().getFullYear()} Alex Doe. All Rights Reserved.`,
  adminBackground: 'admin-bg-1',
};

export const SOCIAL_PLATFORMS: SocialPlatform[] = [
  'website',
  'instagram',
  'tiktok',
  'linkedin',
  'youtube',
  'twitter',
  'github'
];

export const ADMIN_BACKGROUNDS = [
  { value: 'admin-bg-1', name: 'Subtle Grid' },
  { value: 'admin-bg-2', name: 'Polka Dots' },
  { value: 'admin-bg-3', name: 'Blueprint' },
  { value: 'admin-bg-4', name: 'Cosmic' },
  { value: 'admin-bg-5', name: 'Crosses' },
  { value: 'admin-bg-6', name: 'Pinstripes' },
  { value: 'admin-bg-7', name: 'Wigwam' },
  { value: 'admin-bg-8', name: 'Circuit' },
  { value: 'admin-bg-9', name: 'Bubbles' },
  { value: 'admin-bg-10', name: 'Graph Paper' },
  { value: 'admin-bg-11', name: 'Animated Gradient' },
  { value: 'admin-bg-12', name: 'Rotating Cone' },
  { value: 'admin-bg-13', name: 'Aurora' },
  { value: 'admin-bg-14', name: 'Intersecting Lines' },
  { value: 'admin-bg-15', name: 'Galaxy' },
  { value: 'admin-bg-16', name: 'Moving Pixels' },
  { value: 'admin-bg-17', name: 'Subtle Radial' },
  { value: 'admin-bg-18', name: 'Moving Checkers' },
  { value: 'admin-bg-19', name: 'Cyber Circles' },
  { value: 'admin-bg-20', name: 'Scan Line' },
  { value: 'admin-bg-21', name: 'Dark Towers' },
  { value: 'admin-bg-22', name: 'Indigo Diamond' },
  { value: 'admin-bg-23', name: 'Corner Dots' },
  { value: 'admin-bg-24', name: 'Slate Gradient' },
  { value: 'admin-bg-25', 'name': 'Golden Star' },
  { value: 'admin-bg-26', name: 'Liquid' },
  { value: 'admin-bg-27', 'name': 'Stone Grid' },
  { value: 'admin-bg-28', 'name': 'Green Hex' },
  { value: 'admin-bg-29', name: 'Diamond Dust' },
  { value: 'admin-bg-30', 'name': 'Plus Pattern' },
  { value: 'admin-bg-31', 'name': 'Slate Dots' },
  { value: 'admin-bg-32', 'name': 'Slate Radial' },
  { value: 'admin-bg-33', 'name': 'Floating Orbs' },
  { value: 'admin-bg-34', 'name': 'Dual Radial' },
  { value: 'admin-bg-35', 'name': 'Golden Hex' },
  { value: 'admin-bg-36', name: 'Plaid' },
  { value: 'admin-bg-37', name: 'Diagonal Lines' },
  { value: 'admin-bg-38', 'name': 'Dark Grid' },
  { value: 'admin-bg-39', 'name': 'Layered Grid' },
  { value: 'admin-bg-40', 'name': 'Argyle' },
  { value: 'admin-bg-41', name: 'Gradient Spotlight' },
  { value: 'admin-bg-42', name: 'Stripes' },
  { value: 'admin-bg-43', name: 'Dotted' },
  { value: 'admin-bg-44', 'name': 'Checkerboard' },
  { value: 'admin-bg-45', name: 'Blue Dots' },
  { value: 'admin-bg-46', name: 'Repeating Argyle' },
  { value: 'admin-bg-47', name: 'Diagonal Gradient' },
  { value: 'admin-bg-48', 'name': 'Purple Dots' },
  { value: 'admin-bg-49', 'name': 'Micro Grid' },
  { value: 'admin-bg-50', 'name': 'Abstract Tech' },
];
